name: "PR Reviews CI"

on: 
  # Chaos ahead, PROCEED AT YOUR OWN RISK!
  pull_request_target:
    types: 
      - assigned
      - unassigned
      - labeled
      - unlabeled
      - edited
      - opened
      - synchronize
      - locked
      - unlocked
      - review_requested
      - review_request_removed

jobs:
  automated-reviews:
    name: Automated PR Reviews
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          # Just don't cache the cursed $GITHUB_TOKEN
          persist-credentials: false
          # IDK about how we should test Dangerfile changes for now.
          repository: 'RecapTime/verify'
          ref: 'main'
          # We want them all
          fetch-depth: 0

      # TODO: Upgrade to 16.x when it reaches the Active LTS status.
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: '14'

      # We should be fine, as long as our repo's main branch is cloned, right?
      # Unless shit happens in the caches.
      - name: Install Node.js packages
        run: yarn install

      - name: Run Danger JS
        run: yarn ci:dangerjs-github
        env:
          # We'll use an seperate PAT without access to private repos. As usual,
          # please use GH_SERVICE_ACCOUNT_API_KEY action secret for private repos.
          DANGER_GITHUB_API_TOKEN: ${{secrets.DANGER_GITHUB_TOKEN}}
